Repository Hanghae99-Ten/Ten-FE, pull requests merged in 2024-01, with the labels that each got.

#6 header 작업
  src/assets/icons/Calendar.svg
  src/assets/icons/Edit.svg
  src/assets/icons/PP_Header_Logo.svg
  src/assets/icons/PlusButton.svg
  src/assets/icons/Search.svg
  src/assets/icons/Share.svg
  src/assets/icons/svg.d.ts
  src/components/index.ts
  src/components/layout/DarkModeToggle.tsx
  src/components/layout/PostHeader.tsx
  src/layout/Header.tsx
  src/layout/Layout.tsx
  src/layout/index.ts
  src/pages/Post.tsx
  src/pages/index.ts
  src/shared/Router.tsx
  src/store/atom.ts
  src/store/index.ts
  vite.config.ts
Labels: Work In Progress

#10 회원가입 작업
  src/pages/SignUp.tsx
  src/pages/index.ts
  src/shared/Router.tsx
Labels: Seonjung, Work In Progress

#16 FE 공용 디자인 추가
  src/components/common/Card.tsx
  src/components/common/DefaultCard.tsx
  src/components/common/MainCard.tsx
  src/components/common/index.tsx
  src/layout/Layout.tsx
  src/pages/Home.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: Jihun
